### ISSUE TITLE
SSO broken

### ISSUE THREAD

**Issue by paswa** [ohaz/amos-ss15-proj1#52]
When I try to use SSO login (i.e. Google+ and Facebook) from the load balancer (http://amos1.endless-aerospace.de/login?next=%2Findex) the SSO services tell me the following:

Google: Invalid parameter value for redirect_uri: Non-public domains not allowed: http://amos1/login_google/authorized

Facebook: Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by paswa** [comment]
When accessing the clouds directly (not via the load balancer) I get the following results:

AWS: works as intended
Azure: Facebook works. Google button does not seem to do anything except reloading the page.
Google: Neither Facebook nor Google work. Error messages as stated in my previous comment.

**Comment by ohaz** [comment]
Facebook should now work. Please confirm. Also, somebody has to set the valid oauth redirect URLs for google.

**Comment by ohaz** [comment]
Load balancer now uses a domain system that allows for SSO to work. Google oauth token needs to be applied though.

Why facebook login just redirects to the login page, I don't know. Somebody here to investigate?

**Comment by ayeks** [comment]
Thanks to the new configs and SSO parameters it works now. When the SSO registration fails, issue #51 is the cause. See that issue for more information.
